### ISSUE TITLE
Fails when LIFX app is running in the background

### ISSUE THREAD

**Issue by iheart2code** [besherman/lifx-sdk-java#10]
Steps to reproduce:
1. Install & configure LIFX app
2. Press home button to send LIFX to background
3. Run an app with this SDK set to look for lights

Expected results:
We should see an accurate listing of the connected lights on the LAN.

Actual results:
LFXClient connection fails with the folowing exception: `bind failed: EADDRINUSE (Address already in use)`

Explanation:
You need to set port reuse when [setting up your reader socket](https://github.com/besherman/lifx-sdk-java/blob/master/src/main/java/com/github/besherman/lifx/impl/network/LFXNetworkLoopConnection.java#L190-L191). You can see that the existing LIFX SDK [does this currently](https://github.com/LIFX/lifx-sdk-android/blob/master/library/src/lifx/java/android/network_context/internal/transport_manager/gateway_connection/LFXSocketTCP.java#L98).

**Comment by besherman** [comment]
Excellent! I was having problems with this flag before, when I was binding a specific address. But now it looks like it works just fine. Thanks!

**Comment by besherman** [comment]
Are you running this on Android?

**Comment by iheart2code** [comment]
Yes. Running it with gradle was working fine, but had to get rid of all the awt Color references to get it to build from source.
