### ISSUE TITLE
Add helper methods to LFXGroup

### ISSUE THREAD

**Issue by iheart2code** [besherman/lifx-sdk-java#14]
It would be convenient to have helper methods on LFXGroup that returned the power state of a particular group.

- `isPower()` would return true if any lights are on, otherwise false
- `getColor()` not sure how to handle this one, honestly

**Comment by besherman** [comment]
lifx-sdk-android solved this by:
* "fuzzy power" where the result can be on, off or mixed. 
* averaging the colors. 

Maybe adding `getFuzzyPower()` and `getAverageColor()` to LFXGroup?

**Comment by iheart2code** [comment]
Awesome! Super helpful. Thanks for the quick updates!
