### ISSUE TITLE
Add access to unique group ID

### ISSUE THREAD

**Issue by iheart2code** [besherman/lifx-sdk-java#18]
It looks like the LFXLight instances each get their own consistent, accessible, unique identifiers. Is it possible to add this the LFXGroup as well?

**Comment by besherman** [comment]
Yes, I added this to LFXGroupImpl.java:
```java
public String getID() { return getTagID().toString(); }
```

Before I fixed it I wrote this. But when I got to the end I realized that I should just add it, so I did. Someone might still be interested in how groups are implemented so I posted it anyway.

The the bulb's id is its mac address, which the protocol uses to address it. So exposing that through the api is a no brainer.

Groups on the other hand are not part of the protocol. Groups are created on top of tags (which are in the  protocol) and tags works like this:

* A bulb has a bitfield which indicates which tags it has. There are 64 different tags that the bulb can have. These tags are enumerated in [LFXTagID](https://github.com/besherman/lifx-sdk-java/blob/master/src/main/java/com/github/besherman/lifx/impl/entities/internal/LFXTagID.java). 
* A bulb has a label for each tag. 

So it is technically possible to have two bulbs both having TAG_01 but bulb one thinks that the label for TAG_01 is "A" and bulb two thinks that the label for TAG_01 is "B".

lifx-sdk-android didn't like a tag system, so they implemented groups on top of tags:
* A group is a tag. That is, it's id is the tag.
* When creating/changing a group's label all bulbs are told to change the label for that tag.
* There can not be two groups with the same label.
* A group can not have an empty label.

Personally I like tags better than groups, but I wanted to be compatible with other apps so I went with groups. 

All this comes down to: exposing the tag id through the api is probably fine.
