### ISSUE TITLE
setBroadcast(true) on DatagramSocket stopped SocketException

### ISSUE THREAD

**Issue by austinwylie** [besherman/lifx-sdk-java#19]
I was getting `SEVERE: Failed to send message` with `java.net.SocketException: Permission denied` until I added `channel.socket().setBroadcast(true);` to LFXNetworkLoopConnection.java.

[This post](http://w3facility.org/question/setbroadcast-method/#answer-10168854) was one of the few relevant explanations I discovered, which led me to the DatagramSocket documentation saying [some OSs have permission issues with broadcasts until that flag is set.](http://docs.oracle.com/javase/7/docs/api/java/net/DatagramSocket.html#setBroadcast(boolean)) I'm running OS X 10.10.1 (Yosemite).

**Comment by iheart2code** [comment]
This has been resolved in https://github.com/besherman/lifx-sdk-java/pull/12

**Comment by austinwylie** [comment]
I believe these may be separate problems -- my experience isn't the same as #12, at least. Even with the socket set for address reuse, here's my stack trace:

`java.net.SocketException: Permission denied
at sun.nio.ch.DatagramChannelImpl.send0(Native Method)
at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:532)
at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:509)
at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:473)
at LFXNetworkLoopConnection$Writer.run(LFXNetworkLoopConnection.java:157)`

**Comment by iheart2code** [comment]
Ah, yeah it looks like you're right. I'm going to try adding the setBroadcast(true) call and see if it affects the the behavior at all.

**Comment by iheart2code** [comment]
Did you add that method call into the LFXNetworkLoopConnection.Writer class or the LFXNetworkLoopConnection.Reader class?

**Comment by austinwylie** [comment]
Sounds good. I put it in the Writer.
