### ISSUE TITLE
Discovery listeners don't behave as expected

### ISSUE THREAD

**Issue by iheart2code** [besherman/lifx-sdk-java#24]
Steps to reproduce:
1. Instantiate an LFXClient -- `LFXClient client = new LFXClient();`
2. Implement & set listeners for new and removed lights and groups
3. Open an LFXClient with blocking disabled -- `client.open(false);`
4. On light/group add, add device to list on screen
5. On light/group remove, remove device from list on screen

Expected results:
We should see all lights and groups display on the screen and remain until the user kills power to the LIFX bulbs.

Actual results:
The devices never display in the list because lightRemoved/groupRemoved fire immediately after lightAdded/groupAdded.

Workaround:
Set a delay for clearing "removed" devices from the list view. Delay can be cleared upon the next call to lightAdded/groupAdded (10-15 seconds).

**Comment by besherman** [comment]
I'm guessing that this and #28 is caused by the same problem.
