### ISSUE TITLE
Groups losing their bulbs over time

### ISSUE THREAD

**Issue by joakimar** [besherman/lifx-sdk-java#28]
I have 6 bulbs connected to my network. I am running lifx-sdk-java from HEAD on linux.

I notice that when I first create the LFXClient class, its "all" collection has 6 bulbs and the groups add up to 6 as well.

Over time, say a few minutes, the groups gradually lose all their bulbs so they end up empty (0 bulbs). The "all" collection however, still retains all 6.

Any known problem about how group/tag membership is discovered?

**Comment by iheart2code** [comment]
I've seen this happen as well. Takes a few minutes, but it happens.

**Comment by besherman** [comment]
Hmm, interesting! I'll have a look tonight after work.

**Comment by besherman** [comment]
Okay, fingers crossed this now work properly. Turns out the bulbs are a bit tricky with the groups and the tags and all that. When a light does not have a tag it will tell you that the tag label is empty. That is now hopefully accounted for.

Could you guys check to see if it works for you?

**Comment by iheart2code** [comment]
Will be able to check this evening, US west coast time.

**Comment by iheart2code** [comment]
Do you think this will also fix #25 ?
