### ISSUE TITLE
Detach this fork from lifx-sdk-android

### ISSUE THREAD

**Issue by besherman** [besherman/lifx-sdk-java#9]
Since this project no longer resembles anything like lifx-sdk-android it should probably be [detached](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork) and become it's own project.

**Comment by iheart2code** [comment]
I would agree. Would suggest doing it soon since you'll lose the watchers/stars and issues.
